### PR TITLE
Added test and test config

### PR DESCRIPTION
**Pull request by FritsvanCampen**
Hi. I want to start using this library but it doesn't have any tests yet.
I added a test config with support for jsx and typescript.
Test runner is jest, using babel to compile to js.

### CODE REVIEW

**Comment by sunknudsen** [comment]
Hey @FritsvanCampen, thanks for the PR.

I agree adding tests is a great idea! Can you please [allow](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) me to edit PR?

I believe enabling “Allow edits from maintainers” should work.

Thanks,

Sun

**Comment by FritsvanCampen** [comment]
Hi Sun,

The checkmark is on so you should have edit permissions already.
Is there another setting somewhere else?

image

**Comment by sunknudsen** [comment]
Hey @FritsvanCampen, apparently, I [can’t edit](https://stackoverflow.com/questions/68898874/how-to-test-and-edit-someone-s-pull-request-using-visual-studio-code-and-push-su) your PR without you adding me as a collaborator to your fork.

I ended up [building](https://github.com/sunknudsen/react-node-to-string/pull/3) on your contribution… let me know what you think. 🤓

**Comment by FritsvanCampen** [comment]
I made a PR earlier this week on another project and that seemed to work fine: https://github.com/webonyx/graphql-php/pull/916
The checkbox does seem to imply it does exactly what you would expect.
I've found the UI for adding collaborators but I can't imagine that's the right way to do this.

I will close this PR.
Thanks!

**Comment by sunknudsen** [comment]
@FritsvanCampen I believe checkbox works only if one edits PR using GitHub website (and perhaps apps).

**Pull request closed without merging**
